### ISSUE TITLE
CrystalClear not working BT 1.3.1, RT 996 P1

### ISSUE THREAD

**Issue by GuiltySchism** [gnivler/CrystalClear#4]
Ohai gnivler, your lovely cristal clear is no longer working with the new BT patch :(

**Comment by gnivler** [comment]
Thanks for reporting the issue.  It's apparently working for me with 1.3.1 and CCC.  Have you tried it with a reduced mod configuration?  I'd be interested to know if it's specific to RT somehow.  Are you getting any exceptions in output_log.txt?
