### ISSUE TITLE
hmmm....1.4?

### ISSUE THREAD

**Issue by teknowarmachine** [gnivler/CrystalClear#5]
I kind of feel silly to ask this, i am kind of new to github and i'm rushing around (honestly, i joined because of this very mod):

i was just humbly hoping that maybe you can save me some time and clarify this does work in 1.4 and I'm just being a noob because i am about 75% sure I'm noobing this up.  This is the most important mod in existence, at least for me, my film grain hate is STRONG.  I know i've gotten this to work last year a few patches back....

**Comment by gnivler** [comment]
Yes it works with 1.4

**Comment by teknowarmachine** [comment]
SMH, Yeah, it was me.  A stupid mistake on my end from being too hasty, thanks for the quick reply and eye protection

**Comment by gnivler** [comment]
Glad you got it.  Thanks - enjoy!
