### ISSUE TITLE
Should this mod work with 1.5?

### ISSUE THREAD

**Issue by faceleg** [gnivler/CrystalClear#6]
Using the version downloaded from [Nexus](https://www.nexusmods.com/battletech/mods/273?tab=files) as it seems more up to date than the latest release on GitHub, and the settings below, I'm getting an unexpected result. Are the screenshots attached the expected effect?

Using versions:
 - BATTLETECH 1.5.1-477R
 - ModTek 0.71

Mission: Data Liberation

Other mods:
 - BattleTechPerformanceFix
 - SkipIntro
 - Turbine
 - cFixes-1.5.0.1

```json
{
    "Name": "CrystalClear",
    "Version": "2.0",
    "Enabled": true,

    "DLL": "CrystalClear.dll",

    "Settings": {
        "Grain": false,                 /* reduces clarity when enabled */
        "Dithering": false,             /* reduces clarity when enabled */
        "Vignette": true,               /* darkens the edges of the scene */
        "Bloom": true,                  /* makes light sources overblown when enabled */
        "Shadows": true,                /* can fully disable */
        "ChromaticAberration": true,    /* unsure if used.  it should appear as green/purple edge tinting */
        "EyeAdaptation": false,         /* simulates pupil dilation response */
        "Fog": false,                   /* setting to true makes everywhere foggy */
        "ColorGrading": true,           /* unsure */
        "AmbientOcclusion": true,       /* looks so good I wouldn't disable it */
        "Taa": true,                    /* temporal antialiasing aka MFAA - good fidelity */
        "DepthOfField": true,           /* stuff at different distances is focused differently (blurred) */
        "Fxaa": true,                   /* almost-free light anti-aliasing */
        "HDR": true,                    /* renderer is expecting this to be on but works without */
        "Grunge": false,                 /* dirty UI */
        "Scanlines": false,              /* scanline animation on UI */

    }
}
```

With CrystalClear
![Screenshot (3)](https://user-images.githubusercontent.com/1000759/56286124-07b2d200-616d-11e9-96e1-fa5cb9539764.png)

**Comment by gnivler** [comment]
Hmm ...It's been a while, but yeah maybe.  The mech visibility is poor, is
that what you're thinking is abnormal?  If so have you seen it on other
maps?  Just to eliminate weather, not sure it could cause that effect.  The
mod appears a least partially effective insofar as UI grunge and scanlines
are gone.  Grain's a bit trickier in a still pic but also looks gone.  Your
mod.json settings look fine to me.

**Comment by faceleg** [comment]
I tried to take a comparison screenshot, the main issue for me is the glow effect that you can see everwhere - this screenshot is closer to what the map looks like when CrystalClear is turned off:

![fcc32184446f6c50db8f8f09855c881547537eaf_2_690x388](https://user-images.githubusercontent.com/1000759/56324102-052e9780-61c2-11e9-9ac6-acb2f3f19069.jpg)

The glowing effect seen in my first screenshot makes it pretty hard to see anything with any detail. I can turn "bloom" off, but that makes everything look totally dull, which is again very different to vanilla.

**Comment by gnivler** [comment]
I see what you mean I think; it's kind of muddy.  Was this previously working?  I haven't recompiled the binary for a while that'd be worth a shot for sure.  I'll attach it here for you to test if you wish.. Calling it 2.3 alpha but it's just a recompile against the newest assembly.

Second screenshot is too small to make out the detail unfortunately, but overall I see its difference.

This is a shot of mine with similar settings to yours, wrong biome unfortunately.

![image](https://user-images.githubusercontent.com/18452645/56325268-d6b3ac80-612e-11e9-8d48-2084b4ce2f15.png)


Download to test:
[CrystalClear2.2.zip](https://github.com/gnivler/CrystalClear/files/3091815/CrystalClear2.2.zip)


I hope it works!

**Comment by faceleg** [comment]
Thank you so much! I'll try this out tonight.

Another thing I've thought of trying is compiling a version that doesn't attempt to modify bloom at all, I'm giving it a go but am on macOS until I get home and don't think it'll compile in that version of Visual Studio :)

**Comment by gnivler** [comment]
It's good timing kinda, no worries.  Only takes a second to make that change actually.  Good idea, not sure if it'll help either way.  Are you playing on a Mac?

[CrystalClear2.31 no bloom control.zip](https://github.com/gnivler/CrystalClear/files/3091842/CrystalClear2.31.no.bloom.control.zip)

**Comment by faceleg** [comment]
No, on Windows 10, we use Mac at work.

**Comment by faceleg** [comment]
If that does anything, then another idea I had was to change the Settings values from being bools to an enum (or a string if this language doesn't like string enums), with values "On", "Off" and "Ignore", where "Ignore" doesn't do anything at all.

I'll report back when I've tried both, I'll make sure I load saves on a few different map types as well.

**Comment by gnivler** [comment]
That is another good idea.  The code is pretty simple, just repetitive.  Should be doable even by me!  Maybe.

Thanks for testing it out!

**Comment by faceleg** [comment]
No problem - having this (lol) tri-state boolean would also mean that users can cause the mod to leave completely alone effects they're happy with keeping vanilla.

**Comment by gnivler** [comment]
Agreed, much better.

**Comment by faceleg** [comment]
Something like this?

```c#
namespace CrystalClear
{
    public class Settings
    {
        public string Dithering;
        public string Grain;
        public string Vignette;
        public string Bloom;
        public string UIBloom;
        public string Shadows;
        public string ChromaticAberration;
        public string EyeAdaptation;
        public string Fog;
        public string ColorGrading;
        public string AmbientOcclusion;
        public string Taa;
        public string DepthOfField;
        public string Fxaa;
        public string HDR;
        public string Grunge;
        public string Scanlines;
        public string enableDebug;
    }

    public static class CrystalClear
    {
        public static Settings modSettings;
        public static string modDirectory;
        public const string ON = "On";
        public const string OFF = "Off";
        public const string IGNORE = "Ignore";

        public static void Init(string modDirectory, string settingsJson)
        {
            FileLog.logPath = Path.Combine(modDirectory, "log.txt");
            Clear();
            var harmony = HarmonyInstance.Create("ca.gnivler.CrystalClear");
            //HarmonyInstance.DEBUG = false;
            harmony.PatchAll(Assembly.GetExecutingAssembly());
            try
            {
                CrystalClear.modDirectory = modDirectory;
                modSettings = JsonConvert.DeserializeObject<Settings>(settingsJson);
            }
            catch (Exception e)
            {
                Error(e);
            }

            if (modSettings.Grunge == ON || modSettings.Scanlines == ON) return;
            if (modSettings.Grunge == IGNORE || modSettings.Scanlines == IGNORE) return;

            int mainTex = Shader.PropertyToID("_MainTex");
            Type uniformsType = AccessTools.Inner(typeof(BTPostProcess), "Uniforms");
            if (modSettings.Grunge == OFF)
            {
                AccessTools.Field(uniformsType, "_GrungeTex").SetValue(null, mainTex);
            }

            if (modSettings.Scanlines == OFF)
            {
                AccessTools.Field(uniformsType, "_ScanlineTex").SetValue(null, mainTex);
            }

            if (modSettings.Dithering == OFF)
            {
                AccessTools.Field(uniformsType, "_DitheringTex").SetValue(null, 0);
            }
        }

        [HarmonyPatch(typeof(BTPostProcess), "OnEnable", MethodType.Normal)]
        public static class BTPostProcess_Ctor_Patch
        {
            public static void Postfix(ref float ___uiBloomIntensity)
            {
                if (modSettings.UIBloom == OFF)
                {
                    ___uiBloomIntensity = 0f;
                    LogDebug("Patching UI bloom");
                }
            }
        }
    }
}
```

**Comment by faceleg** [comment]
@gnivler I've submitted a quick PR, I can't (and don't know how anyway) compile, but if you pull the PR down, compile and upload a binary I can test later tonigh.

**Comment by gnivler** [comment]
Right on, thanks.  We have the same code more or less, so I'll just make
sure I grok your contribution and merge it with mine manually.

I have enum all worked out, except I think the mod.json settings doesn't
appear to support enum.  So back to strings and a bunch of ugly repeating
code!

**Comment by faceleg** [comment]
Cool, the other thing I noticed is I think you have to return true from the overrides else the original method doesn’t get called? That was my interpretation of the harmony doc page I linked to in my pr

**Comment by gnivler** [comment]
Yeah it was a shortcut because the bool translated directly.. Here's the long form solution I believe.

```[HarmonyPatch(typeof(DitheringComponent), "active", MethodType.Getter)]
public static class PatchDitheringComp
{
    public static bool Prefix(ref bool __result)
    {
        // implicitly does nothing if 'NOTSET'
        switch (modSettings.Dithering)
        {
            case "ON":
            {
                LogDebug("Patching dithering");
                __result = true;
                break;
            }
            case "OFF":
            {
                LogDebug("Patching dithering");
                __result = false;
                break;
            }
        }
        return false;
    }
}```

**Comment by gnivler** [comment]
I believe I've got it.  New mod.json config, "ON" or "OFF" does that, anything else runs vanilla.  I used NOTSET /shrug.

[CrystalClear2.4.zip](https://github.com/gnivler/CrystalClear/files/3092065/CrystalClear2.4.zip)

**Comment by faceleg** [comment]
I’ll try it tonight and report back, amazing!

**Comment by faceleg** [comment]
Tried just now, got this error: 

> ModTek v0.7.1 -- 4/18/2019 7:10:34 PM
> Loaded config.
> Loaded cached load order.
> 
> BattletechPerformanceFix 
> 	Loaded assembly BattletechPerformanceFix (v2.7.0.28460)
> 	Invoking 'Main.Start(String modDirectory, String json)' using parameter dictionary
> cFixes 1.5.0.1
> 	255 manifest entries
> SkipIntro 1.4.0
> 	Loaded assembly SkipIntro (v1.4.0.38408)
> 	Invoking 'Main.Init()' using parameter dictionary
> Turbine 1.0.0
> 	Loaded assembly Turbine (v2.0.0.10)
> 	Invoking 'Mod.Init()' using parameter dictionary
> CrystalClear 2.41
> 	Loaded assembly CrystalClear (v2.41.0.0)
> 	Invoking 'CrystalClear.Init(String modDirectory, String settingsJson)' using parameter dictionary
> 	Error: While invoking 'CrystalClear.Init', an exception occured
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path "C:\log.txt" is denied.
>   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) [0x00000] in <filename unknown>:0 
>   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share) [0x00000] in <filename unknown>:0 
>   at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
>   at System.IO.StreamWriter..ctor (System.String path, Boolean append, System.Text.Encoding encoding, Int32 bufferSize) [0x00000] in <filename unknown>:0 
>   at System.IO.StreamWriter..ctor (System.String path, Boolean append) [0x00000] in <filename unknown>:0 
>   at (wrapper remoting-invoke-with-check) System.IO.StreamWriter:.ctor (string,bool)
>   at CrystalClear.Logger.Clear () [0x00000] in <filename unknown>:0 
>   at CrystalClear.CrystalClear.Init (System.String modDirectory, System.String settingsJson) [0x00000] in <filename unknown>:0 
>   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
>   --- End of inner exception stack trace ---
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
>   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
>   at ModTek.Util.AssemblyUtil.InvokeMethodByParameterNames (System.Reflection.MethodInfo method, System.Collections.Generic.Dictionary`2 paramsDictionary) [0x00000] in <filename unknown>:0 
>   at ModTek.ModTek.LoadAssemblyAndCallInit (ModTek.ModDef modDef) [0x00000] in <filename unknown>:0 
> 
> Adding Mod Content...
> Loaded type cache.

**Comment by faceleg** [comment]
I think it must be this: https://github.com/gnivler/CrystalClear/blob/2.4/CrystalClear.cs#L43

**Comment by faceleg** [comment]
OK I've installed VS, commented out the logging to get past this crash and tried it with only Grain & Dithering NO, the rest NOTSET.

This is the result, very happy:

![BATTLETECHScreenshot00000_2](https://user-images.githubusercontent.com/1000759/56351857-1e673080-6222-11e9-8ec2-e23ed3f3d934.png)

**Comment by faceleg** [comment]
Update - looks great on the forest tileset too, this update fixes my issue (still won't load if I uncomment the logger though)

**Comment by gnivler** [comment]
Ah that Harmony logging mechanism has bit more times... it works OK for some and not others.  I will comment it out, thanks for the find/fix.

Glad it's working better!  Awesome.

**Comment by faceleg** [comment]
Let me know when you’ve got a release, I’ll use my local hack build for now :)

**Comment by faceleg** [comment]
Scratch that I see you’ve put one up. Thanks!

**Comment by faceleg** [comment]
Just tried the latest release, log.txt error:

```CrystalClear 2.41
	Loaded assembly CrystalClear (v2.42.0.0)
	Invoking 'CrystalClear.Init(String modDirectory, String settingsJson)' using parameter dictionary
	Error: While invoking 'CrystalClear.Init', an exception occured
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path "C:\log.txt" is denied.```

**Comment by gnivler** [comment]
Well that sucks!  I hope it was my error compiling because there's no reference to log.txt anywhere in the code anymore, odd.

Here's a fresh "identical" compile, if you wouldn't mind giving it a whirl.  They all work OK on mine or I'd test it too.  Any chance you have UAC enabled?

[CrystalClear2.43.zip](https://github.com/gnivler/CrystalClear/files/3098265/CrystalClear2.43.zip)

**Comment by gnivler** [comment]
Just figured it out I believe... posting update shortly.

**Comment by gnivler** [comment]
This should do it!

[CrystalClear2.45.zip](https://github.com/gnivler/CrystalClear/files/3099332/CrystalClear2.45.zip)

**Comment by faceleg** [comment]
Works great! Closing this issue now, thank you _so much_!
